services:
  postgres:
    container_name: spring_blog
    image: postgres:17.5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: spring_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: